
FROM python
# FROM grimloc13/yolo-detection:v02 # For rebuild

# Linux Packages

RUN apt-get update
RUN apt-get install libgl1 tree nano htop -y

# Project Directory

COPY ./Yolo /Yolo

# Python Packages

RUN pip3 install -r /Yolo/requirements.txt
RUN pip3 install ultralytics

