
FROM python

# For rebuild:
# FROM grimloc13/detr-detection:v01
# RUN rm -rf ./home/YOLOv8

# Linux Packages

RUN apt-get update
RUN apt-get install libgl1 tree nano htop -y

# Project Directory

COPY ./DETR /home/DETR

# Python Packages

RUN pip3 install -r /home/DETR/requirements.txt
RUN pip3 install ultralytics

RUN pip install timm
RUN pip install tensorboard
