
FROM python

# For rebuild:
# FROM grimloc13/detr-detection:v02
# RUN rm -rf ./home/DETR

# Linux Packages

RUN apt-get update
RUN apt-get install libgl1 tree nano htop -y

# Project Directory

COPY ./DETR /home/DETR

# Python Packages

RUN pip3 install -r /home/DETR/requirements.txt
